# Generated by Django 3.1.5 on 2021-01-30 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='sme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='bugtracker.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patron', to='bugtracker.organization'),
            preserve_default=False,
        ),
    ]
