# Generated by Django 3.1.5 on 2021-01-31 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0002_auto_20210130_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patron', to='bugtracker.organization'),
        ),
    ]
