# Generated by Django 3.1.5 on 2021-02-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0004_bug_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='severity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default=None, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='type',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Performance', 'Performance'), ('Usability', 'Usability'), ('Compatability', 'Compatability'), ('Security', 'Security'), ('Other', 'Other')], default=None, max_length=13, null=True),
        ),
    ]
